// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using VcwBackend.Core;

namespace VcwBackend.Migrations
{
    [DbContext(typeof(ApiContext))]
    partial class ApiContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("VcwBackend.Models.Attachment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<Guid?>("CategoryId");

                    b.Property<DateTime>("CreateDate");

                    b.Property<bool>("Deleted");

                    b.Property<string>("Description");

                    b.Property<string>("FileName");

                    b.Property<DateTime>("ModifDate");

                    b.Property<string>("Type");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Attachments");
                });

            modelBuilder.Entity("VcwBackend.Models.Category", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("CategoryName");

                    b.Property<DateTime>("CreateDate");

                    b.Property<bool>("Deleted");

                    b.Property<DateTime>("ModifDate");

                    b.HasKey("Id");

                    b.ToTable("Categories");
                });

            modelBuilder.Entity("VcwBackend.Models.Challenge", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("ChallengeState");

                    b.Property<string>("ChallengeType");

                    b.Property<string>("CompanyName");

                    b.Property<DateTime>("CreateDate");

                    b.Property<DateTime?>("Deadline")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Deleted");

                    b.Property<string>("Description");

                    b.Property<decimal?>("FirstBounce");

                    b.Property<DateTime>("ModifDate");

                    b.Property<decimal?>("SecondBounce");

                    b.Property<decimal?>("ThirdBounce");

                    b.Property<string>("Title");

                    b.HasKey("Id");

                    b.ToTable("Challenges");
                });

            modelBuilder.Entity("VcwBackend.Models.Comment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("CreateDate");

                    b.Property<bool>("Deleted");

                    b.Property<string>("Description");

                    b.Property<DateTime>("ModifDate");

                    b.HasKey("Id");

                    b.ToTable("Comments");
                });

            modelBuilder.Entity("VcwBackend.Models.Filter", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("CreateDate");

                    b.Property<bool>("Deleted");

                    b.Property<string>("Description");

                    b.Property<Guid>("InviteId");

                    b.Property<DateTime>("ModifDate");

                    b.Property<string>("Title");

                    b.HasKey("Id");

                    b.HasIndex("InviteId");

                    b.ToTable("Filters");
                });

            modelBuilder.Entity("VcwBackend.Models.Idea", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("CreateDate");

                    b.Property<bool>("Deleted");

                    b.Property<string>("Description");

                    b.Property<Guid?>("InvitId");

                    b.Property<Guid?>("InviteId");

                    b.Property<DateTime>("ModifDate");

                    b.Property<string>("Title");

                    b.HasKey("Id");

                    b.HasIndex("InviteId");

                    b.ToTable("Ideas");
                });

            modelBuilder.Entity("VcwBackend.Models.Invite", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<Guid?>("ChallengeId");

                    b.Property<DateTime>("CreateDate");

                    b.Property<bool>("Deleted");

                    b.Property<bool?>("IsMaster");

                    b.Property<DateTime>("ModifDate");

                    b.Property<Guid?>("UserId");

                    b.HasKey("Id");

                    b.HasIndex("ChallengeId");

                    b.HasIndex("UserId");

                    b.ToTable("Invites");
                });

            modelBuilder.Entity("VcwBackend.Models.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Company");

                    b.Property<DateTime>("CreateDate");

                    b.Property<bool>("Deleted");

                    b.Property<string>("Email");

                    b.Property<string>("FirstName");

                    b.Property<string>("LastName");

                    b.Property<DateTime>("ModifDate");

                    b.Property<string>("Password");

                    b.Property<byte[]>("ProfileImage");

                    b.Property<string>("Title");

                    b.Property<string>("Username");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("VcwBackend.Models.Attachment", b =>
                {
                    b.HasOne("VcwBackend.Models.Category", "Category")
                        .WithMany("Attachments")
                        .HasForeignKey("CategoryId");
                });

            modelBuilder.Entity("VcwBackend.Models.Filter", b =>
                {
                    b.HasOne("VcwBackend.Models.Invite", "Invite")
                        .WithMany("Filters")
                        .HasForeignKey("InviteId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("VcwBackend.Models.Idea", b =>
                {
                    b.HasOne("VcwBackend.Models.Invite", "Invite")
                        .WithMany("Ideas")
                        .HasForeignKey("InviteId");
                });

            modelBuilder.Entity("VcwBackend.Models.Invite", b =>
                {
                    b.HasOne("VcwBackend.Models.Challenge", "Challenge")
                        .WithMany("Invites")
                        .HasForeignKey("ChallengeId");

                    b.HasOne("VcwBackend.Models.User", "User")
                        .WithMany("Invites")
                        .HasForeignKey("UserId");
                });
#pragma warning restore 612, 618
        }
    }
}
